### ISSUE TITLE
Docker image borked?

### ISSUE THREAD

**Issue by jackmac92** [Onboardbase/securelog-scan#57]
Tried switching to the image for CI in my personal projects but it failed. Debugging locally I found:

```
docker run ghcr.io/onboardbase/securelog-scan:main

docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "securelog-scan": executable file not found in $PATH: unknown.
```
Using `docker inspect ghcr.io/onboardbase/securelog-scan:main` I see the entrypoint is `securelog-scan`
But running the container with `docker run --entrypoint=/bin/sh ghcr.io/onboardbase/securelog-scan:main` it appears only `sls` is available (so the executable not found makes sense)

(I ran a docker pull before testing so above should all be up to date)

**Comment by iamnasirudeen** [comment]
Hi there, thanks for reporting this, issue has been fixed, you can run docker pull again to install

**Comment by dantelex** [comment]
@jackmac92 Thanks for catching this. Do let us know if you have any other feedback
